/**
 * A machine-readable format for specifying errors in HTTP API responses based on https://tools.ietf.org/html/rfc7807.
 */
export interface IProblemDetails {
  /**
   * A URI reference [RFC3986] that identifies the problem type.
   * This specification encourages that, when dereferenced, it provides human-readable
   * documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028]).
   */
  readonly type: string;

  /**
   * The HTTP status code ([RFC7231], Section 6) generated by the origin server for
   * this occurrence of the problem.
   */
  readonly status: number;

  /**
   * A short, human-readable summary of the problem type.
   * It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes
   * of localization (e.g., using proactive content negotiation; see[RFC7231], Section 3.4).
   */
  readonly title: string;

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  readonly details: string | undefined;

  /**
   * A URI reference that identifies the specific occurrence of the problem.
   * It may or may not yield further information if dereferenced.
   */
  readonly instance: string;

  /**
   * Problem type definitions MAY extend the problem details object with additional members.
   * Clients consuming problem details MUST ignore any such extensions that they don't recognize;
   * this allows problem types to evolve and include additional information in the future.
   */
  readonly extensions: Record<string, any> | undefined;
}

export class ProblemDetails implements IProblemDetails {
  constructor(
    readonly type: string,
    readonly status: number,
    readonly title: string,
    readonly details: string | undefined,
    readonly instance: string,
    readonly extensions: Record<string, any> | undefined
  ) {}

  toPlain(): Record<string, any> {
    const plain: Record<string, any> = {
      type: this.type,
      status: this.status,
      title: this.title,
      details: this.details,
      instance: this.instance,
    };

    if (this.extensions) {
      for (const key of Object.keys(this.extensions)) {
        plain[key] = this.extensions[key];
      }
    }

    return plain;
  }

  static from(obj: IProblemDetails): ProblemDetails {
    return new ProblemDetails(
      obj.type,
      obj.status,
      obj.title,
      obj.details,
      obj.instance,
      obj.extensions
    );
  }
}

export interface IProblemDetailsBuilder {
  withType(type: string): this;
  withStatus(status: number): this;
  withTitle(title: string): this;
  withDetails(details: string | undefined): this;
  withInstance(instance: string): this;
  withExtensions(extensions: Record<string, any> | undefined): this;
  addExtensions(extensions: Record<string, any>): this;
  setExtension<T>(key: string, value: T): this;
  build(): IProblemDetails;
}

export class ProblemDetailsBuilder implements IProblemDetailsBuilder {
  private type: string | undefined;
  private status: number | undefined;
  private title: string | undefined;
  private details: string | undefined;
  private instance: string | undefined;
  private extensions: Record<string, any> | undefined;

  withType(type: string): this {
    this.type = type;
    return this;
  }

  withStatus(status: number): this {
    this.status = status;
    return this;
  }

  withTitle(title: string): this {
    this.title = title;
    return this;
  }

  withDetails(details: string | undefined): this {
    this.details = details;
    return this;
  }

  withInstance(instance: string): this {
    this.instance = instance;
    return this;
  }

  withExtensions(extensions: Record<string, any> | undefined): this {
    this.extensions = extensions;
    return this;
  }

  addExtensions(extensions: Record<string, any>): this {
    this.extensions = { ...this.extensions, ...extensions };
    return this;
  }

  setExtension<T>(key: string, value: T): this {
    return this.addExtensions({ [key]: value });
  }

  build(): IProblemDetails {
    return new ProblemDetails(
      this.type ?? "Unknown",
      this.status ?? 0,
      this.title ?? "Unknown",
      this.details,
      this.instance ?? "Unknown",
      this.extensions
    );
  }
}
