export { Constructor, isConstructor } from "./Constructor";
export { Guid, InvalidGuidError } from "./Guid";
export { Predicate } from "./Predicate";
export { Result, ResultFailure, ResultSuccess } from "./Result";
export { constructorOf } from "./constructorOf";
export { dot } from "./dot";
export { flatten } from "./flatten";
export { isFunction } from "./isFunction";
export { isInRange } from "./isInRange";
export { isNotNull } from "./isNotNull";
export { merge } from "./merge";
export { IPipe, Transform, pipe } from "./pipe";
export { timeout } from "./timeout";
