name: Publish @tomasjs/amqplib

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/packages-amqplib-cicd.yml
      - packages/amqplib/src/**
      - packages/amqplib/package.json

jobs:
  cicd:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          token: ${{secrets.NPM_ACCESS_TOKEN}}

      - name: Install modules
        run: |
          cd ./packages/amqplib
          npm install

      - name: Build
        run: |
          cd ./packages/amqplib
          npm run compile

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
        run: |
          cd ./packages/amqplib
          npm run publish
