name: Publish to NPM

on:
  push:
    branches:
      - dev
    paths:
      - .github/workflows/packages-express-npm-publish.yml
      - packages/express/src
      - packages/express/package.json

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build source code
        run: |
          cd ./packages/express
          npm run compile

  publish:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Publish build to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
        run: |
          cd ./packages/express
          npm run publish
