name: Test @tomasjs/core

on:
  pull_request:
    branches:
      - release/v2
    paths:
      - .github/workflows/packages-core-test.yml
      - packages/core/src/**
      - packages/core/package.json

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          token: ${{secrets.NPM_ACCESS_TOKEN}}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install modules
        run: |
          cd ./packages/core
          pnpm install

      - name: Run tests
        run: |
          cd ./packages/core
          pnpm test
