name: Publish to NPM

on:
  push:
    branches:
      - dev
    paths:
      - packages/express/src
      - packages/express/package.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Go into /packages/express directory
        run: cd ./packages/express

      - name: Build source code
        run: npm run compile

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Go into /packages/express directory
        run: cd ./packages/express

      - name: Publish build to NPM
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
