name: Publish @tomasjs/core to NPM

on:
  push:
    branches:
      - dev
    paths:
      - .github/workflows/packages-core-npm-publish.yml
      - packages/core/src/**
      - packages/core/package.json

jobs:
  prepare:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          token: ${{secrets.NPM_ACCESS_TOKEN}}

      - name: Install modules
        run: |
          cd ./packages/core
          npm install

  test:
    runs-on: windows-latest
    needs: prepare
    steps:
      - name: Run tests
        run: |
          cd ./packages/core
          npm run test

  build:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Build
        run: |
          cd ./packages/core
          npm run compile

  publish:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
        run: |
          cd ./packages/core
          npm run publish
